// Generated by CoffeeScript 2.6.1
//###########################################################
var service;

service = null;

export var setService = function(serviceToSet) {
  return service = serviceToSet;
};

//###########################################################
export var addNodeId = async function(publicKey, timestamp, signature) {
  await service.addNodeId(publicKey);
  return {
    ok: true
  };
};


//###########################################################
export var removeNodeId = async function(publicKey, timestamp, signature) {
  await service.removeNodeId(publicKey);
  return {
    ok: true
  };
};

//###########################################################
export var getSecretSpace = async function(publicKey, timestamp, signature) {
  var eCE, eCIS, rE, rIS, secretObj;
  secretObj = (await service.getEncryptedSecretSpace(publicKey));
  rE = secretObj.referencePointHex != null;
  eCE = secretObj.encryptedContentHex != null;
  rIS = typeof secretObj.referencePointHex === "string";
  eCIS = typeof secretObj.encryptedContentHex === "string";
  if (rE && eCE && rIS && eCIS) {
    return secretObj;
  }
  /*   
   {
       "referencePointHex": "...",
       "encryptedContentHex": "..."
   }
   */
  throw new Error("Service returned wrong secret object format.");
};

//###########################################################
export var getSecret = async function(publicKey, secretId, timestamp, signature) {
  var eCE, eCIS, rE, rIS, secretObj;
  secretObj = (await service.getSecret(publicKey, secretId));
  rE = secretObj.referencePointHex != null;
  eCE = secretObj.encryptedContentHex != null;
  rIS = typeof secretObj.referencePointHex === "string";
  eCIS = typeof secretObj.encryptedContentHex === "string";
  if (rE && eCE && rIS && eCIS) {
    return secretObj;
  }
  /*   
   {
       "referencePointHex": "...",
       "encryptedContentHex": "..."
   }
   */
  throw new Error("Service returned wrong secret object format.");
};


//###########################################################
export var setSecret = async function(publicKey, secretId, secret, timestamp, signature, req) {
  var urlToSync;
  urlToSync = service.getURLToSync(publicKey);
  if (urlToSync != null) {
    syncToURL(req);
  }
  await service.setSecret(publicKey, secretId, secret);
  return {
    ok: true
  };
};

//###########################################################
export var deleteSecret = async function(publicKey, secretId, timestamp, signature, reqData) {
  await service.deleteSecret(publicKey, secretId);
  return {
    ok: true
  };
};

//###########################################################
export var startAcceptingSecretsFrom = async function(publicKey, fromId, timestamp, signature, reqData) {
  await service.addSubSpaceFor(publicKey, fromId);
  return {
    ok: true
  };
};

//###########################################################
export var stopAcceptingSecretsFrom = async function(publicKey, fromId, timestamp, signature) {
  await service.removeSubSpaceFor(publicKey, fromId);
  return {
    ok: true
  };
};

//###########################################################
export var shareSecretTo = async function(publicKey, shareToId, secretId, secret, timestamp, signature) {
  await service.shareSecretTo(publicKey, shareToId, secretId, secret);
  return {
    ok: true
  };
};

//###########################################################
export var deleteSharedSecret = function(publicKey, sharedToId, secretId, timestamp, signature) {
  service.deleteSharedSecret(sharedToId, publicKey, secretId);
  return {
    ok: true
  };
};

//###########################################################
export var addNotificationHook = async function(publicKey, type, specific, timestamp, signature) {
  await service.addNotificationHook(publicKey, type, specific);
  return {
    ok: true
  };
};

//###########################################################
export var getAuthCode = async function(publicKey, timestamp, signature) {
  var authCode;
  authCode = (await service.generateAuthCodeFor(publicKey));
  if (typeof authCode === "string") {
    return {authCode};
  }
  /*   
   {
       "authCode": "..."
   }
   */
  throw new Error("Service returned wrong authCode type.");
};

//###########################################################
export var addFriendServer = async function(authCode, serverURL, serverNodeId) {
  await service.addFriendServer(serverURL, serverNodeId);
  return {
    ok: true
  };
};

//###########################################################
export var getNodeId = async function(authCode) {
  var pKE, pKEIS, result, sE, sEIS, tSE, tSEIS;
  result = (await service.getSignedNodeId());
  pKE = result.publicKey != null;
  tSE = result.timestamp != null;
  sE = result.signature != null;
  pKEIS = typeof result.publicKey === "string";
  tSEIS = typeof result.timestamp === "string";
  sEIS = typeof result.signature === "string";
  if (pKE && tSE && sE && pKEIS && tSEIS && sEIS) {
    return result;
  }
  /*
  {
      "publicKey": "...",
      "timestamp": "...",
      "signature": "..."
  }
  */
  throw new Error("Service returned wrong signedNodeId Object format.");
};
