// Generated by CoffeeScript 2.6.1
import {
  postData
} from "thingy-network-base";

//###########################################################
export var addNodeId = function(sciURL, publicKey, timestamp, signature) {
  var requestObject, requestURL;
  requestObject = {publicKey, timestamp, signature};
  requestURL = sciURL + "/addNodeId";
  return postData(requestURL, requestObject);
};

export var removeNodeId = function(sciURL, publicKey, timestamp, signature) {
  var requestObject, requestURL;
  requestObject = {publicKey, timestamp, signature};
  requestURL = sciURL + "/removeNodeId";
  return postData(requestURL, requestObject);
};

export var getSecretSpace = function(sciURL, publicKey, timestamp, signature) {
  var requestObject, requestURL;
  requestObject = {publicKey, timestamp, signature};
  requestURL = sciURL + "/getSecretSpace";
  return postData(requestURL, requestObject);
};

export var getSecret = function(sciURL, publicKey, secretId, timestamp, signature) {
  var requestObject, requestURL;
  requestObject = {publicKey, secretId, timestamp, signature};
  requestURL = sciURL + "/getSecret";
  return postData(requestURL, requestObject);
};

export var setSecret = function(sciURL, publicKey, secretId, secret, timestamp, signature) {
  var requestObject, requestURL;
  requestObject = {publicKey, secretId, secret, timestamp, signature};
  requestURL = sciURL + "/setSecret";
  return postData(requestURL, requestObject);
};

export var deleteSecret = function(sciURL, publicKey, secretId, timestamp, signature) {
  var requestObject, requestURL;
  requestObject = {publicKey, secretId, timestamp, signature};
  requestURL = sciURL + "/deleteSecret";
  return postData(requestURL, requestObject);
};

export var startAcceptingSecretsFrom = function(sciURL, publicKey, fromId, timestamp, signature) {
  var requestObject, requestURL;
  requestObject = {publicKey, fromId, timestamp, signature};
  requestURL = sciURL + "/startAcceptingSecretsFrom";
  return postData(requestURL, requestObject);
};

export var stopAcceptingSecretsFrom = function(sciURL, publicKey, fromId, timestamp, signature) {
  var requestObject, requestURL;
  requestObject = {publicKey, fromId, timestamp, signature};
  requestURL = sciURL + "/stopAcceptingSecretsFrom";
  return postData(requestURL, requestObject);
};

export var shareSecretTo = function(sciURL, publicKey, shareToId, secretId, secret, timestamp, signature) {
  var requestObject, requestURL;
  requestObject = {publicKey, shareToId, secretId, secret, timestamp, signature};
  requestURL = sciURL + "/shareSecretTo";
  return postData(requestURL, requestObject);
};

export var deleteSharedSecret = function(sciURL, publicKey, sharedToId, secretId, timestamp, signature) {
  var requestObject, requestURL;
  requestObject = {publicKey, sharedToId, secretId, timestamp, signature};
  requestURL = sciURL + "/deleteSharedSecret";
  return postData(requestURL, requestObject);
};

export var addNotificationHook = function(sciURL, publicKey, type, specific, timestamp, signature) {
  var requestObject, requestURL;
  requestObject = {publicKey, type, specific, timestamp, signature};
  requestURL = sciURL + "/addNotificationHook";
  return postData(requestURL, requestObject);
};

export var getAuthCode = function(sciURL, publicKey, timestamp, signature) {
  var requestObject, requestURL;
  requestObject = {publicKey, timestamp, signature};
  requestURL = sciURL + "/getAuthCode";
  return postData(requestURL, requestObject);
};

export var addFriendServer = function(sciURL, authCode, serverURL, serverNodeId) {
  var requestObject, requestURL;
  requestObject = {authCode, serverURL, serverNodeId};
  requestURL = sciURL + "/addFriendServer";
  return postData(requestURL, requestObject);
};

export var getNodeId = function(sciURL, authCode) {
  var requestObject, requestURL;
  requestObject = {authCode};
  requestURL = sciURL + "/getNodeId";
  return postData(requestURL, requestObject);
};
